<?php
# This file was automatically generated by the MediaWiki 1.17.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = 'Deep Blue Robotics Wiki';
$wgMetaNamespace = "My_wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = '';
$wgRunJobsAsync = false;
$wgArticlePath = $wgScriptPath.'/$1';
$wgScriptExtension  = ".php";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/BarLogo.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = 'dbrobotic@a2plcpnl0447.prod.iad2.secureserver.net';
$wgPasswordSender   = 'dbrobotic@a2plcpnl0447.prod.iad2.secureserver.net';

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = 'localhost';
$wgDBname           = 'i2026229_mw2';
$wgDBuser           = 'i2026229_mw2';
$wgDBpassword       = 'U^SccDro5K6B7t5]~A.88@[1';

# MySQL specific settings
$wgDBprefix         = 'mw_';

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of ./languages/Language(.*).php
$wgLanguageCode = 'en';

$wgSecretKey = "50736dba86b274e9c2f2f082044f0b3b01115f855322539d42e5723a2f0c1084";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "a9b5baf10807f677";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";



# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;


# End of automatically generated settings.
# Add more configuration options below.
require_once "$IP/skins/Vector/Vector.php";

require_once("$IP/extensions/AdminLinks/AdminLinks.php");

require_once "$IP/extensions/ConfirmAccount/ConfirmAccount.php";

$wgGroupPermissions['*']['edit'] = false;

$wgShowSQLErrors = 1;

#### Widgets extension ####
require_once "$IP/extensions/Widgets/Widgets.php";

######## WYWSIWIG EXTENSTION CONFIGURATION ########
#02.07.16->
#Enable WYSIWYG- extension, MW >= 1.25
wfLoadExtension( 'WYSIWYG' ); 
#02.07.16<-

#10.11.13->
#Enable WYSIWYG- extension, MW <= 1.24 (with newer versions will use wfLoadExtension, if supported)
#require_once( "$IP/extensions/WYSIWYG/WYSIWYG.php" );
#10.11.13->

#13.11.13->
#WikiEditor may not be compatible with WYSIWYG editor, use it with caution.
#WikiEditor vers. <= 0.4.0
#require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );    

#WikiEditor vers. >= 0.5.0
wfLoadExtension( 'WikiEditor' );

#Use this only with MW<=1.24: tells wysiwyg that text based editor is WikiEditor
#$wgCKEditorWikiEditorActive = true;  

# Examples of setting permissions using $wgGroupPermissions, for more detailed explanation see:
#   https://www.mediawiki.org/wiki/Manual:$wgGroupPermissions#Example
# $wgGroupPermissions['user']['wysiwyg'] = true; //Only registered users are allowed to use wysiwyg
# $wgGroupPermissions['*']['wysiwyg'] = true;    //Everyone is allowed to use wysiwyg
$wgGroupPermissions['*']['wysiwyg'] = true;

$wgDefaultUserOptions['cke_show'] = 'richeditor';    //Enable CKEditor
$wgDefaultUserOptions['riched_use_toggle'] = false;  //Editor can toggle CKEditor/WikiText
$wgDefaultUserOptions['riched_start_disabled'] = false; //Important!!! else bug...
$wgDefaultUserOptions['riched_toggle_remember_state'] = true; //working/bug?
$wgDefaultUserOptions['riched_use_popup'] = false;   //Deprecated

##These are not compatible with WYSIWYG
$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;
#13.11.13<-

#17.01.14-> 
# Enables/disables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;

# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 0;

# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 0;
#17.01.14<-

#27.03.14->
#This was required by SemanticMediaWiki extension in MW 1.22.4 to prevent startup error:
$wgLocalisationUpdateDirectory = "$IP/cache";

#These are for SemanticForms. Wysiwyg is not fully compatiple with SemanticForms and SemanticMediawiki,
#so this is experimental feature.
#enableSemantics( );
#include_once( "$IP/extensions/SemanticForms/SemanticForms.php" );

#Optional excludes of wysiwyg in case SemanticForms and SemanticMediawiki are installed:
#$wgFCKEditorExcludedNamespaces[] = SF_NS_FORM;
#$wgFCKEditorExcludedNamespaces[] = SMW_NS_PROPERTY;
#27.03.14<-

#06.02.15->
#Setting value of following variables eq. to 1 will cause wikitext text blocks
#within specified tags to be displayed as image- element in wysiwyg mode.
#Value eq. to 0 makes texts inside these tags editable directly as text in wysiwyg mode
#using pre- parent tag + child tag.
$wgFCKEditorSpecialElementWithPreTag   = 0; // 1= <pre> tags with attributes only => img- element
#06.02.15<-

#26.02.15->
$wgFCKEditorSpecialElementWithTextTags = 0; // 1= <nowiki>, <source> and <syntaxhighlight> tags => img- element
#26.02.15<-

#24.03.16->
#In case CKEDITOR is installed in some special place, define installation path
#with $wgCKEditor_BASEPATH. If variable is undefined, default value is 'extensions/WYSIWYG/ckeditor/'.
#NOTE! Path must end with character '/' in linux (opsys. windows is untested).
#$wgCKEditor_BASEPATH = 'extensions/WYSIWYG/ckeditor/';

#Debug- mode of resource loader (use only for testing purposes):
#$wgResourceLoaderDebug = true;
#24.03.16<-

#17.04.16->
#In case source files of WYSIWYG/CKeditor are used, they will work only if wgWYSIWYGSourceMode is set to true.
#NOTE! At this point source- mode of WYSIWYG/Ckeditor does not use resourceloaded of MW.
#$wgWYSIWYGSourceMode = true;
#17.04.16<-

